### ISSUE TITLE
UX: apply new color styles 

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#1018]
Apply new styles to the app:

https://material.io/tools/color/#!/?view.left=0&amp;view.right=0&view.right=1&primary.color=247BA0&secondary.color=32936F&secondary.text.color=ffffff

https://github.com/dasfoo/delern/pull/1017

Design Link: https://www.figma.com/file/GpB4q0mTtA2Ndyn9ohszmXki/Delern-app-designs?node-id=27%3A2
Prototype Link: https://www.figma.com/proto/GpB4q0mTtA2Ndyn9ohszmXki/Delern-app-designs?scaling=scale-down

New design screenshots:
https://github.com/dasfoo/delern/tree/gssoc19/New%20design%20screenshots

**Comment by Kvaibhav01** [comment]
I want to work on this. Please un-assign me from #937.

**Comment by ksheremet** [comment]
@Kvaibhav01  ok
