### ISSUE TITLE
UX: design new Edit screen

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#1050]
![edit_screen](https://user-images.githubusercontent.com/6387464/58945328-f3aa4a80-8783-11e9-9d85-ee363baedf1e.jpg)

**Comment by Kateevp** [comment]
![Edit_screen_fixes](https://user-images.githubusercontent.com/51339647/61144359-f90e5980-a4d4-11e9-838d-b797e3eae28a.png)

1. Change the styles of texts: 
    _Deck name:_ 44pt, Bold, #212121
    _info:_ 22pt, #757575   
    Please change the text on the second line from "Number of cards" to "**Cards in this deck**"

2. The layout of the header (resolution 1280*720px):
       empty space - 12px
       deck name container - 62px, text centered
       separator - 2px, colour #c0c0c0
       info container - 48px, text centered
       separator - 2px, colour #c0c0c0
       
   Height of the header total - **124px** (10,3% of the total height of 1280px)

3. The layout of the list of cards:
       Vertically:
              top and bottom margins - 36px
              distance between cards - 16px
              height of cards - 120px
       Horizontally:
              left and right margins - 72px (10%)
              lenght of cards - 576px (80%)

       Colours for cards: #e2f0d2 (green), #ffcfdf (pink), #c7e5fc (blue)

4. New GO UP button:
       background colour #607d8b, the icon is attached
       [Arrow.zip](https://github.com/dasfoo/delern/files/3387389/Arrow.zip)

5. Left and right margins for card texts - 36px
