### ISSUE TITLE
Show dots when user created deck with long name

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#1172]
**Describe the bug**
When the name of the deck has a few lines it is partial visible in appbar
**To Reproduce**
1. Create deck to learn with a few lines of name
2. Go to learning

**Expected behavior**
If the name of a deck is too long, show dots.

**Screenshots**

![WhatsApp Image 2019-09-24 at 22 37 31](https://user-images.githubusercontent.com/6387464/65957225-96ca5280-e44c-11e9-9245-737c180c8429.jpeg)

**Comment by whatsupcoders** [comment]
I have fixed the Long Deck names using the Text Overflow Ellipsis property.
