### ISSUE TITLE
Show 3 dots in Edit Screen when the card is to huge (with a lot of lines)

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#1178]
How it looks now:

![Screenshot_20191001-132851](https://user-images.githubusercontent.com/6387464/65958370-85367a00-e44f-11e9-9743-a0cca2f3c240.png)
![Screenshot_20191001-132843](https://user-images.githubusercontent.com/6387464/65958371-85367a00-e44f-11e9-8c95-8c7cac03854f.png)

**Expected:**
Show 3 dots in the end in edit deck

**Comment by whatsupcoders** [comment]
Fixed Long name cards by using the Text Overflow Ellipsis property and created a reusable widget named "TextOverflowEllipsisWidget" as the same fix on the issue #1172. Also added a extra styling property "primaryTextStyle" which was required for this cards section.

Also updated the property name from "primaryTextStyle" to "textStyle" which make more sense.
