### ISSUE TITLE
Add license (LICENSE or etc)

### ISSUE THREAD

**Issue by dotdoom** [dasfoo/delern#122]
Would make sense to have at least a copyleft license, so that others can't publish copies to Google Play without your consent.

https://f-droid.org/wiki/page/FAQ_-_App_Developers#I_see_apps_on_the_big_stores_that_are_blatant_copies._Wouldn.27t_it_be_better_if_I_made_my_app_closed_source.3F

**Comment by ksheremet** [comment]
This file is part of Delern.

Delern is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License
version 3 of the License.

You should have received a copy of the GNU General Public License
along with Delern.  If not, see <http://www.gnu.org/licenses/>.
