### ISSUE TITLE
Firebase CLI lower than 7.7.0 will need to explicitly grant access through Cloud IAM

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#1265]
After January 15, 2020, if you use any version of the Firebase CLI lower than 7.7.0 to deploy a new HTTP or Callable Cloud Function, that function will require you to explicitly grant public access through Cloud IAM permissions. Existing HTTP Cloud Functions will not be affected by this change.
What's changing?
Due to a Google Cloud Platform change to provide more security and predictability for server-to-server communication, all newly created HTTP Cloud Functions will be private-by-default and require manual configuration using Cloud IAM.
However, since most Cloud Functions created by Firebase users are client application-facing, we have updated the Firebase CLI to maintain the existing behavior and set the permissions for new functions as public.
This change does not affect the functions that have already been deployed. Only new functions deployed after January 15, 2020, using old versions of the CLI, will be affected.
What is the behavior of a private function?
Clients that try to connect will be returned a "403 Forbidden" error.
What’s next?
Before you attempt to deploy any functions, update your Firebase CLI to the latest version (at least 7.7.0, released November 7, 2019), by running:
npm install --global firebase-tools, and then
firebase --version to confirm that you're on a version of 7.7.0 or higher.
Once you have done this, functions deployed with the Firebase CLI will continue to be public by default.
How do I convert my existing functions to private?
If you would like to take advantage of the new functionality to restrict access to your existing HTTP functions, you can do so after deploying it by configuring its permissions.
What if I accidentally deploy functions that are private and want to make them public?
You can manually set a function to public using Cloud Console or gcloud CLI.

**Comment by dotdoom** [comment]
Fixed by updating firebase-cli above 7.7.0:

https://github.com/dasfoo/delern/blob/e9d37f570bfb59d5af6df181bfb0dd06bb6e445e/firebase/package.json#L19
