### ISSUE TITLE
Allow uploading images for cards

### ISSUE THREAD

**Issue by dotdoom** [dasfoo/delern#190]
We can store a limited amount of images in Cloud Storage bucket.

**Comment by ksheremet** [comment]
Design from @Kateevp 

![add_image](https://user-images.githubusercontent.com/6387464/70706636-949b3480-1cd6-11ea-9fbf-370c686efa81.jpeg)
![add_image2](https://user-images.githubusercontent.com/6387464/70706639-97962500-1cd6-11ea-8724-14a051853a62.jpeg)
