### ISSUE TITLE
User.java line 295

### ISSUE THREAD

**Issue by odasfoo** [dasfoo/delern#198]
#### in org.dasfoo.delern.models.User.getChildReference

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/5950c017be077a4dcca0a8fc?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/5950c017be077a4dcca0a8fc?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by dotdoom** [comment]
Tested sign in of new and existing users, no longer reproducible. Most likely fixed with fragment removal.
