### ISSUE TITLE
AbstractOnFBDataChangeListener.java line 57

### ISSUE THREAD

**Issue by odasfoo** [dasfoo/delern#209]
#### in org.dasfoo.delern.models.listeners.AbstractOnFBDataChangeListener.onCancelled

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/595601b8be077a4dccd11e97?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/595601b8be077a4dccd11e97?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by dotdoom** [comment]
Unfortunately, too little debug information. We should update this listener class to also log `mQuery` so we can figure out the path.

**Comment by dotdoom** [comment]
Logging added.
