### ISSUE TITLE
RemoteConfig in SplashActivity

### ISSUE THREAD

**Issue by odasfoo** [dasfoo/delern#213]
#### in com.google.firebase.remoteconfig.zza.onResult

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/595a8fc6be077a4dccfd01c5?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/595a8fc6be077a4dccfd01c5?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by dotdoom** [comment]
Not showing up in 0.2.2+, marking obsolete.
