### ISSUE TITLE
Firebase offline sync is asynchronous

### ISSUE THREAD

**Issue by odasfoo** [dasfoo/delern#273]
#### in com.google.firebase.database.DatabaseError.toException

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/59906256be077a4dcc07dcb1?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/59906256be077a4dcc07dcb1?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by dotdoom** [comment]
No answers in https://stackoverflow.com/questions/46134372/sequencing-firebase-database-offline-sync :\

**Comment by dotdoom** [comment]
Re: offline capabilities:
https://firebase.google.com/docs/database/android/offline-capabilities

We can use transactions:
https://firebase.google.com/docs/database/android/read-and-write#save_data_as_transactions

which are not persisted across app restarts, and implement our own offline sync mechanism by storing data locally:
https://developer.android.com/guide/topics/data/data-storage.html#db

But it sounds like a crazy idea.
