### ISSUE TITLE
LearningCardsActivityPresenter.java line 115

### ISSUE THREAD

**Issue by odasfoo** [dasfoo/delern#278]
#### in org.dasfoo.delern.presenters.LearningCardsActivityPresenter.flipCard

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/59947f46be077a4dcc2d6e36?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/59947f46be077a4dcc2d6e36?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by dotdoom** [comment]
We can fix this by not showing the "flip" button (and card menu) until the first card has arrived.

**Comment by dotdoom** [comment]
Question is why is it not caught in FindBugs `UWF_FIELD_NOT_INITIALIZED_IN_CONSTRUCTOR`
