### ISSUE TITLE
OnOperationCompleteListener.java line 94

### ISSUE THREAD

**Issue by odasfoo** [dasfoo/delern#292]
#### in org.dasfoo.delern.models.listeners.OnOperationCompleteListener.onComplete

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/599d8655be077a4dcc7f16cf?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/599d8655be077a4dcc7f16cf?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by dotdoom** [comment]
Obsolete (OnOperationCompleteListener has been removed)
