### ISSUE TITLE
Rewrite Firebase config as a separate class (with enum options)

### ISSUE THREAD

**Issue by odasfoo** [dasfoo/delern#348]
#### in org.dasfoo.delern.logging.Logger.exception

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/59cc96fbbe077a4dcc61b41a?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/59cc96fbbe077a4dcc61b41a?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by dotdoom** [comment]
For the first bullet point, here's the source location to change:

https://github.com/dasfoo/delern/blob/master/app/src/main/java/org/dasfoo/delern/logging/Logger.java#L275
