### ISSUE TITLE
MultiWrite.java line 181

### ISSUE THREAD

**Issue by odasfoo** [dasfoo/delern#452]
#### in org.dasfoo.delern.models.helpers.MultiWrite.lambda$write$1$MultiWrite

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/5a19aac961b02d480d416118?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/5a19aac961b02d480d416118?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by dotdoom** [comment]
Updated for proper stacktrace.
