### ISSUE TITLE
Add server configuration parameter "min version"

### ISSUE THREAD

**Issue by dotdoom** [dasfoo/delern#46]
To force updates in case of database change or fatal issue.

**Comment by dotdoom** [comment]
Added `min_version`.

Sample usage: https://firebase.google.com/docs/remote-config/android

**Comment by ksheremet** [comment]
1. Firebase remote config doc: https://firebase.google.com/docs/remote-config/use-config-android
2. Good example: https://medium.com/@sembozdemir/force-your-users-to-update-your-app-with-using-firebase-33f1e0bcec5a
