### ISSUE TITLE
SplashScreenActivity.java line 98

### ISSUE THREAD

**Issue by odasfoo** [dasfoo/delern#481]
#### in org.dasfoo.delern.SplashScreenActivity.lambda$onCreate$0$SplashScreenActivity

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/5a337c488cb3c2fa63ea9927?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/5a337c488cb3c2fa63ea9927?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by dotdoom** [comment]
FirebaseRemoteConfigFetchException, no error message. I'd suspect throttling, but it has its own exception type.
