### ISSUE TITLE
Set up licensing

### ISSUE THREAD

**Issue by dotdoom** [dasfoo/delern#52]
https://developer.android.com/google/play/licensing/setting-up.html

**Comment by ksheremet** [comment]
https://stackoverflow.com/questions/18324963/how-can-i-implement-google-play-licensing-for-an-android-app

**Comment by ksheremet** [comment]
https://github.com/PSDev/LicensesDialog

**Comment by dotdoom** [comment]
Licensing is necessary to limit user's ability to interact with application, based on developer-defined "licensed" status of the user. It is not necessary for release / etc, as we don't have any licensed content right now.
