### ISSUE TITLE
DeckViewHolder.java line 99

### ISSUE THREAD

**Issue by odasfoo** [dasfoo/delern#569]
#### in org.dasfoo.delern.listdecks.DeckViewHolder.isDeckAccessNull

* Number of crashes: 1
* Impacted devices: 1

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/5a9916f38cb3c2fa63237eef?utm_medium=service_hooks-github&utm_source=issue_impact](https://fabric.io/dasfoo/android/apps/org.dasfoo.delern/issues/5a9916f38cb3c2fa63237eef?utm_medium=service_hooks-github&utm_source=issue_impact)

**Comment by ksheremet** [comment]
Fixed here: https://github.com/dasfoo/delern/pull/562
