### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by Yasujizr** [dasfoo/delern#615]
![delern flashcard](https://user-images.githubusercontent.com/36993664/38392191-51774f86-392f-11e8-811b-8c87057c299c.jpg)

Hi,

I have studied your work and I think a new design will make you more visible. I designed for you, I hope you like it and you want to use it. If you want to reach me, you can look at the my profile. I can give you all the formats of the design free. If you want a change please specify.

**Comment by ksheremet** [comment]
Hi @Yasujizr, thanks for your design. It looks great! Would it be possible to have more green colors in the logo? Something similar to the color as in the launcher. An example is [here](https://github.com/dasfoo/delern/blob/master/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png).

**Comment by Yasujizr** [comment]
Like this? Or a darker green?

![delern flashcardgreen](https://user-images.githubusercontent.com/36993664/38394118-e2d09626-3935-11e8-9bb8-abc1248ef824.jpg)

**Comment by ksheremet** [comment]
Darker green would be better) Thank you @Yasujizr !

**Comment by Yasujizr** [comment]
![delern flashcard4](https://user-images.githubusercontent.com/36993664/38413935-c1cc05e0-3995-11e8-92cc-2ad82c631bc3.jpg)

How is it now?
@ksheremet

**Comment by ksheremet** [comment]
Perfect @Yasujizr ! Thanks! I'll reach you privately by email.

**Comment by Yasujizr** [comment]
@ksheremet 

I sent the files. I hope you use it. You can write in any problem.
