### ISSUE TITLE
Update firebase_auth plugin and fix some minor issues

### ISSUE THREAD

**Issue by dotdoom** [dasfoo/delern#931]
Flutter's firebase_auth plugin has been heavily rewritten (https://github.com/flutter/plugins/commit/a444ad120418d622c4dea2882190968722abbcfe#diff-24450cd30718eaedff320c60aa64b0c5) recently. We should bump it to a new version, revert our override 
(https://github.com/dasfoo/delern/commit/075d937cbfc3b9d1169edcdfcb45979543a10329) at and perhaps try clearing auth cache on failure (available via https://github.com/flutter/plugins/pull/799).

This may help fix some issues:

* https://sentry.io/share/issue/34bb7752dcfb4b58b8d399ac9e43e628/
* https://sentry.io/share/issue/24995b92b2b0459084df13b910905e79/
* https://sentry.io/share/issue/f583d6a203b945e39021a409d12bf404/

**Comment by jddeep** [comment]
@dotdoom Can you please confirm when shall I start contributing being a part of Gssoc19? I want to gradually resolve all possible issues one after another. Please give me a date for when to start making PRs?
