### ISSUE TITLE
Tests: Create widget test for empty_list_message_widget.dart

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#934]
Create widget test for https://github.com/dasfoo/delern/blob/master/flutter/lib/views/helpers/empty_list_message_widget.dart

Widget test doc: https://flutter.dev/docs/cookbook/testing/widget/introduction

**Comment by jddeep** [comment]
@ksheremet I would like to work on this issue as a part of gssoc19. When shall I consider making a PR?

**Comment by ksheremet** [comment]
@jddeep Thanks for your interest in this project. I'll assign this issue to you. Your contributions will be counted from the 1st of March

**Comment by ksheremet** [comment]
@jddeep Not more than 2. Now you are assigned to 2 issues

**Comment by jddeep** [comment]
@ksheremet i have added the test file. I will make a PR tommorow. But just wanted to say that there is a build failure on my local machine as it seems there is no googleservices.json file.

**Comment by ksheremet** [comment]
@jddeep 

This is [Wiki](https://github.com/dasfoo/delern/wiki/Development-environment-for-mobile-app) that explains how to configure the project and get `google-services.json`. Have you tried it?
