### ISSUE TITLE
Accessibility: Support accessibility for Card Preview screen

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#938]
Make sure that accessibility is supported for:
`delern/flutter/lib/views/card_preview/card_preview.dart`
      
       
**Doc**: https://flutter.dev/docs/development/accessibility-and-localization/accessibility
**Tooltip - Widget of the week**: https://www.youtube.com/watch?v=EeEfD5fI-5Q

**Comment by jddeep** [comment]
@ksheremet I would work on this.
