### ISSUE TITLE
Accessibility: Support accessibility for Card learning screen

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#939]
Make sure that accessibility is supported for:
`delern/flutter/lib/views/cards_learning/cards_learning.dart`
             

**Doc**: https://flutter.dev/docs/development/accessibility-and-localization/accessibility
**Tooltip - Widget of the week**: https://www.youtube.com/watch?v=EeEfD5fI-5Q

**Comment by jddeep** [comment]
@ksheremet I would like to work on this.
