### ISSUE TITLE
Accessibility: Support accessibility for Deck Settings screen

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#941]
Make sure that accessibility is supported for screen:
`delern/flutter/lib/views/deck_settings/deck_settings.dart`
      
 
**Doc**: https://flutter.dev/docs/development/accessibility-and-localization/accessibility
**Tooltip - Widget of the week**: https://www.youtube.com/watch?v=EeEfD5fI-5Q

**Comment by jddeep** [comment]
@ksheremet I would like to work on this as my second issue.
