### ISSUE TITLE
Accessibility: Support accessibility for Deck Sharing screen

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#942]
Make sure that accessibility is supported for screen:
`delern/flutter/lib/views/deck_sharing/deck_sharing.dart`
      
       

**Doc**: https://flutter.dev/docs/development/accessibility-and-localization/accessibility
**Tooltip - Widget of the week**: https://www.youtube.com/watch?v=EeEfD5fI-5Q

**Comment by jddeep** [comment]
@ksheremet I would like to work with this. Can I?

**Comment by jddeep** [comment]
@ksheremet @dotdoom please confirm and kindly assign. Cheers!
