### ISSUE TITLE
Accessibility: Support accessibility for List of Decks screen

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#943]
Make sure that accessibility is supported for:
`delern/flutter/lib/views/decks_list/decks_list.dart`
`delern/flutter/lib/views/decks_list/create_deck_widget.dart`
      
      
      
**Doc**: https://flutter.dev/docs/development/accessibility-and-localization/accessibility
**Tooltip - Widget of the week**: https://www.youtube.com/watch?v=EeEfD5fI-5Q

**Comment by Kvaibhav01** [comment]
@ksheremet, I can work on this. Do we need to add the `Tooltip` widget only for accessibility?

**Comment by ksheremet** [comment]
@Kvaibhav01 Yes, it is yours. 
Once you accept collaborators invite, I'll add you to Assignees.

To solve this issue please have a look at Docs links that are provided above
