### ISSUE TITLE
Add sign in method with Facebook

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#944]

**Comment by ayush221b** [comment]
Hi, Can I claim this issue?

**Comment by ksheremet** [comment]
@ayush221b Sure, it is yours now! Once you accept collaborators invite I'll add you to Assignees

**Comment by ayush221b** [comment]
I accepted it just now.

**Comment by dotdoom** [comment]
Hint: in #953, I have left some hints as to where new provider support has to be done in the code. Look for `#944` in `flutter/lib/remote/auth.dart`.

**Comment by ksheremet** [comment]
Hi @ayush221b 

How is it getting on with the issue?

**Comment by Ramanpreet6262** [comment]
Pls assign this issue to me
