### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by dotdoom** [dasfoo/delern#954]
Flutter Firebase plugins are migrating to AndroidX, e.g. [firebase_auth](https://pub.dartlang.org/packages/firebase_auth#080).

We have to prepare the app to be able to use new versions of the plugins:
https://developer.android.com/jetpack/androidx/migrate

**Comment by yashk2000** [comment]
Can I please try working on this @dotdoom ?

**Comment by jddeep** [comment]
@dotdoom I would like to work with this.

**Comment by jddeep** [comment]
@dotdoom Can I make a PR for the same?

**Comment by dotdoom** [comment]
Hi @jddeep, sorry for delayed response - I was out of office. You can surely make a PR, but note that this issue is not labeled for gssoc19, so it will not give you points for that. We could not estimate the difficulty as it requires updating all the plugins (!) and carefully studying their changelogs. I was going to work on it later this week.

**Comment by jddeep** [comment]
Okay @dotdoom In that case I guess I have to leave it to you now. Cause I am focusing mainly on Gssoc19 right now. Hope you understand. :)
