### ISSUE TITLE
UX: Suggest colors for App(primary, accent, secondary, etc)

### ISSUE THREAD

**Issue by ksheremet** [dasfoo/delern#971]
Create a new design for the app with colors that provides good accessibility. Consider good contrast
For example:
Now:
![Screenshot_20190314-121828](https://user-images.githubusercontent.com/6387464/54353283-e9305700-4653-11e9-9cb5-9707f787c201.png)

Background color and foreground color have not a good contrast. Therefore accessibility scanner shows warnings. 
Example of fixing it by changing primary color:
![Screenshot_20190314-115823](https://user-images.githubusercontent.com/6387464/54353391-36acc400-4654-11e9-8e3a-59b04dce0c55.png)

__TODO:__
1. Use (Material Design)[https://material.io/]
1. Consider to keep all colors and styles in https://github.com/dasfoo/delern/blob/master/flutter/lib/flutter/styles.dart
1. Move hardcoded colors from [main.dart](https://github.com/dasfoo/delern/blob/master/flutter/lib/main.dart#L44) in file provided above (styles.dart)
1. Suggest new colors for text, foreground, etc
1. Do not forget to add a screenshot with your PR

__Useful links:__
- https://flutter.dev/docs/development/accessibility-and-localization/accessibility
- Accessibility Scanner - https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=en
- https://medium.com/flutter-community/a-deep-dive-into-flutters-accessibility-widgets-eb0ef9455bc
- https://codelabs.developers.google.com/codelabs/mdc-103-flutter/index.html?index=..%2F..index#0

**Comment by vsharma20v** [comment]
Is this issue is about designing UI or doing some enhancement in style using the dart language?
I'm asking this because I have no experience in dart but can help u choosing colours and designing UI.

**Comment by ksheremet** [comment]
@vsharma20v 
Thanks for your interest!
This issue is choosing colors (primary, secondary, accent, text color, etc)

**Comment by vsharma20v** [comment]
@ksheremet  can I work on that.

**Comment by ksheremet** [comment]
@vsharma20v 
Great!
Yes, you can work on it

**Comment by ksheremet** [comment]
@vsharma20v 

Please accept collaborators invitation and I can add you to assignees

**Comment by vsharma20v** [comment]
Accepted

**Comment by ksheremet** [comment]
Hi @vsharma20v 

How is it getting on with the issue?

**Comment by vsharma20v** [comment]
Hi @ksheremet  sorry for being late but here are the following colour themes I like the most:

https://material.io/tools/color/#!/?view.left=0&amp;view.right=0&view.right=0&primary.color=9575cd&primary.text.color=ffffff&secondary.color=FFB74D&secondary.text.color=ffffff


https://material.io/tools/color/#!/?view.left=0&amp;view.right=0&view.right=1&primary.color=247BA0&secondary.color=32936F&secondary.text.color=ffffff

I personally like the first one what about your opinion?

**Comment by vsharma20v** [comment]
@ksheremet  Do I need to design the prototype also with new color themes?

**Comment by ksheremet** [comment]
@vsharma20v , (Do I need to design the prototype also with new color themes?) - yes

I prefer the second one

**Comment by vsharma20v** [comment]
> @vsharma20v , (Do I need to design the prototype also with new color themes?) - yes
> 
> I prefer the second one

OK I will create the prototype with the colour theme you like

**Comment by vsharma20v** [comment]
@ksheremet 
Design Link: https://www.figma.com/file/GpB4q0mTtA2Ndyn9ohszmXki/Delern-app-designs?node-id=27%3A2
Prototype Link: https://www.figma.com/proto/GpB4q0mTtA2Ndyn9ohszmXki/Delern-app-designs?scaling=scale-down
