### ISSUE TITLE
Update Android icon with new specifications

### ISSUE THREAD

**Issue by dotdoom** [dasfoo/delern#990]
Current (left), new (middle), current displayed in compatibility mode (right).

![image](https://user-images.githubusercontent.com/561122/55215673-e197b300-51fa-11e9-9f1a-f3d98d041de8.png)

https://android-developers.googleblog.com/2019/03/introducing-new-google-play-app-and.html

**Comment by Ramanpreet6262** [comment]
@dotdoom in this issue do i need to update icon acc. to Google's new update?
